### PR TITLE
New version for commit 615351eee830708b9680b65e1819a311f09891d9.

### PR DESCRIPTION
**Pull request by martinrotter**

### CODE REVIEW

**Comment by martinrotter** [comment]
bot, build pr

**Comment by martinrotter** [comment]
bot, build io.github.martinrotter.textosaurus

**Comment by martinrotter** [comment]
bot, build io.github.martinrotter.textosaurus

**Comment by TingPing** [comment]
It is just `bot, build` btw.

**Comment by martinrotter** [comment]
@TingPing Thank you, bro. Struggling. :D But semi-automatic generation of JSON file + appdata version update works nicely.

**Pull request merged**
